spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: xxxxxxxxxx
    password: xxxxxxxxxx
    driver-class-name: org.postgresql.Driver
  jooq:
    sql-dialect: POSTGRES